### ISSUE TITLE
game can not be launched after applzing ac2 patch

### ISSUE THREAD

**Issue by gituser823** [begin-theadventure/acfix#1]
hello,

I followed the script and installed the steam common redistributable (was already installed).
And made the patch executable and executed it.

Now when I try to launch the game I get the Error "Failed to request product key from steam, please try again in a few mintues." constantly.

How do I fix this?
The Game runs fine my Windows installation.

**Comment by begin-theadventure** [comment]
Honestly I don't know why it isn't working for you.
I just tried it and it worked. Maybe try this:
1) Close Steam
Delete: `appinfo.vdf` `localization.vdf` `packageinfo.vdf` in the directory: ~/.local/share/Steam/appcache
Start Steam -> Start AC2 -> Close Steam -> Apply the [fix](https://github.com/begin-theadventure/acfix/releases/tag/AC2)

**Comment by gituser823** [comment]
I got it working by following this workaround:
https://github.com/ValveSoftware/Proton/issues/190#issuecomment-951908035

**Comment by begin-theadventure** [comment]
Apparently Valve fixed it: `https://github.com/ValveSoftware/steam-for-linux/issues/212#issuecomment-1084935133`
